global:
  resolve_timeout: 5m

route:
  receiver: snowpanel-warning
  group_by: ["alertname", "severity", "instance"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 2h
  routes:
    - receiver: snowpanel-critical
      matchers:
        - severity="critical"
    - receiver: snowpanel-warning
      matchers:
        - severity="warning"

receivers:
  - name: snowpanel-warning
    webhook_configs:
      - url: "https://example.com/alert-webhook-warning"
        send_resolved: true

  - name: snowpanel-critical
    webhook_configs:
      - url: "https://example.com/alert-webhook-critical"
        send_resolved: true

inhibit_rules:
  - source_matchers:
      - severity="critical"
    target_matchers:
      - severity="warning"
    equal: ["alertname", "instance"]
