// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: proto/agent/v1/agent.proto

package agentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SystemService_GetSystemOverview_FullMethodName   = "/snowpanel.agent.v1.SystemService/GetSystemOverview"
	SystemService_GetRealtimeResource_FullMethodName = "/snowpanel.agent.v1.SystemService/GetRealtimeResource"
)

// SystemServiceClient is the client API for SystemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SystemServiceClient interface {
	GetSystemOverview(ctx context.Context, in *GetSystemOverviewRequest, opts ...grpc.CallOption) (*GetSystemOverviewResponse, error)
	GetRealtimeResource(ctx context.Context, in *GetRealtimeResourceRequest, opts ...grpc.CallOption) (*GetRealtimeResourceResponse, error)
}

type systemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemServiceClient(cc grpc.ClientConnInterface) SystemServiceClient {
	return &systemServiceClient{cc}
}

func (c *systemServiceClient) GetSystemOverview(ctx context.Context, in *GetSystemOverviewRequest, opts ...grpc.CallOption) (*GetSystemOverviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSystemOverviewResponse)
	err := c.cc.Invoke(ctx, SystemService_GetSystemOverview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) GetRealtimeResource(ctx context.Context, in *GetRealtimeResourceRequest, opts ...grpc.CallOption) (*GetRealtimeResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRealtimeResourceResponse)
	err := c.cc.Invoke(ctx, SystemService_GetRealtimeResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemServiceServer is the server API for SystemService service.
// All implementations must embed UnimplementedSystemServiceServer
// for forward compatibility.
type SystemServiceServer interface {
	GetSystemOverview(context.Context, *GetSystemOverviewRequest) (*GetSystemOverviewResponse, error)
	GetRealtimeResource(context.Context, *GetRealtimeResourceRequest) (*GetRealtimeResourceResponse, error)
	mustEmbedUnimplementedSystemServiceServer()
}

// UnimplementedSystemServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSystemServiceServer struct{}

func (UnimplementedSystemServiceServer) GetSystemOverview(context.Context, *GetSystemOverviewRequest) (*GetSystemOverviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSystemOverview not implemented")
}
func (UnimplementedSystemServiceServer) GetRealtimeResource(context.Context, *GetRealtimeResourceRequest) (*GetRealtimeResourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRealtimeResource not implemented")
}
func (UnimplementedSystemServiceServer) mustEmbedUnimplementedSystemServiceServer() {}
func (UnimplementedSystemServiceServer) testEmbeddedByValue()                       {}

// UnsafeSystemServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemServiceServer will
// result in compilation errors.
type UnsafeSystemServiceServer interface {
	mustEmbedUnimplementedSystemServiceServer()
}

func RegisterSystemServiceServer(s grpc.ServiceRegistrar, srv SystemServiceServer) {
	// If the following call pancis, it indicates UnimplementedSystemServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SystemService_ServiceDesc, srv)
}

func _SystemService_GetSystemOverview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSystemOverviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).GetSystemOverview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemService_GetSystemOverview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).GetSystemOverview(ctx, req.(*GetSystemOverviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_GetRealtimeResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRealtimeResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).GetRealtimeResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemService_GetRealtimeResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).GetRealtimeResource(ctx, req.(*GetRealtimeResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SystemService_ServiceDesc is the grpc.ServiceDesc for SystemService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SystemService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "snowpanel.agent.v1.SystemService",
	HandlerType: (*SystemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSystemOverview",
			Handler:    _SystemService_GetSystemOverview_Handler,
		},
		{
			MethodName: "GetRealtimeResource",
			Handler:    _SystemService_GetRealtimeResource_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/agent/v1/agent.proto",
}

const (
	HealthService_Check_FullMethodName = "/snowpanel.agent.v1.HealthService/Check"
)

// HealthServiceClient is the client API for HealthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HealthServiceClient interface {
	Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type healthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthServiceClient(cc grpc.ClientConnInterface) HealthServiceClient {
	return &healthServiceClient{cc}
}

func (c *healthServiceClient) Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, HealthService_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthServiceServer is the server API for HealthService service.
// All implementations must embed UnimplementedHealthServiceServer
// for forward compatibility.
type HealthServiceServer interface {
	Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedHealthServiceServer()
}

// UnimplementedHealthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHealthServiceServer struct{}

func (UnimplementedHealthServiceServer) Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedHealthServiceServer) mustEmbedUnimplementedHealthServiceServer() {}
func (UnimplementedHealthServiceServer) testEmbeddedByValue()                       {}

// UnsafeHealthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthServiceServer will
// result in compilation errors.
type UnsafeHealthServiceServer interface {
	mustEmbedUnimplementedHealthServiceServer()
}

func RegisterHealthServiceServer(s grpc.ServiceRegistrar, srv HealthServiceServer) {
	// If the following call pancis, it indicates UnimplementedHealthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HealthService_ServiceDesc, srv)
}

func _HealthService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).Check(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HealthService_ServiceDesc is the grpc.ServiceDesc for HealthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HealthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "snowpanel.agent.v1.HealthService",
	HandlerType: (*HealthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _HealthService_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/agent/v1/agent.proto",
}

const (
	FileService_ListFiles_FullMethodName       = "/snowpanel.agent.v1.FileService/ListFiles"
	FileService_ReadTextFile_FullMethodName    = "/snowpanel.agent.v1.FileService/ReadTextFile"
	FileService_ReadFileChunk_FullMethodName   = "/snowpanel.agent.v1.FileService/ReadFileChunk"
	FileService_WriteFileChunk_FullMethodName  = "/snowpanel.agent.v1.FileService/WriteFileChunk"
	FileService_WriteTextFile_FullMethodName   = "/snowpanel.agent.v1.FileService/WriteTextFile"
	FileService_CreateDirectory_FullMethodName = "/snowpanel.agent.v1.FileService/CreateDirectory"
	FileService_DeleteFile_FullMethodName      = "/snowpanel.agent.v1.FileService/DeleteFile"
	FileService_RenameFile_FullMethodName      = "/snowpanel.agent.v1.FileService/RenameFile"
)

// FileServiceClient is the client API for FileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileServiceClient interface {
	ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error)
	ReadTextFile(ctx context.Context, in *ReadTextFileRequest, opts ...grpc.CallOption) (*ReadTextFileResponse, error)
	ReadFileChunk(ctx context.Context, in *ReadFileChunkRequest, opts ...grpc.CallOption) (*ReadFileChunkResponse, error)
	WriteFileChunk(ctx context.Context, in *WriteFileChunkRequest, opts ...grpc.CallOption) (*WriteFileChunkResponse, error)
	WriteTextFile(ctx context.Context, in *WriteTextFileRequest, opts ...grpc.CallOption) (*WriteTextFileResponse, error)
	CreateDirectory(ctx context.Context, in *CreateDirectoryRequest, opts ...grpc.CallOption) (*CreateDirectoryResponse, error)
	DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error)
	RenameFile(ctx context.Context, in *RenameFileRequest, opts ...grpc.CallOption) (*RenameFileResponse, error)
}

type fileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileServiceClient(cc grpc.ClientConnInterface) FileServiceClient {
	return &fileServiceClient{cc}
}

func (c *fileServiceClient) ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFilesResponse)
	err := c.cc.Invoke(ctx, FileService_ListFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) ReadTextFile(ctx context.Context, in *ReadTextFileRequest, opts ...grpc.CallOption) (*ReadTextFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadTextFileResponse)
	err := c.cc.Invoke(ctx, FileService_ReadTextFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) ReadFileChunk(ctx context.Context, in *ReadFileChunkRequest, opts ...grpc.CallOption) (*ReadFileChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadFileChunkResponse)
	err := c.cc.Invoke(ctx, FileService_ReadFileChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) WriteFileChunk(ctx context.Context, in *WriteFileChunkRequest, opts ...grpc.CallOption) (*WriteFileChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteFileChunkResponse)
	err := c.cc.Invoke(ctx, FileService_WriteFileChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) WriteTextFile(ctx context.Context, in *WriteTextFileRequest, opts ...grpc.CallOption) (*WriteTextFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteTextFileResponse)
	err := c.cc.Invoke(ctx, FileService_WriteTextFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) CreateDirectory(ctx context.Context, in *CreateDirectoryRequest, opts ...grpc.CallOption) (*CreateDirectoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDirectoryResponse)
	err := c.cc.Invoke(ctx, FileService_CreateDirectory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFileResponse)
	err := c.cc.Invoke(ctx, FileService_DeleteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) RenameFile(ctx context.Context, in *RenameFileRequest, opts ...grpc.CallOption) (*RenameFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenameFileResponse)
	err := c.cc.Invoke(ctx, FileService_RenameFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileServiceServer is the server API for FileService service.
// All implementations must embed UnimplementedFileServiceServer
// for forward compatibility.
type FileServiceServer interface {
	ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error)
	ReadTextFile(context.Context, *ReadTextFileRequest) (*ReadTextFileResponse, error)
	ReadFileChunk(context.Context, *ReadFileChunkRequest) (*ReadFileChunkResponse, error)
	WriteFileChunk(context.Context, *WriteFileChunkRequest) (*WriteFileChunkResponse, error)
	WriteTextFile(context.Context, *WriteTextFileRequest) (*WriteTextFileResponse, error)
	CreateDirectory(context.Context, *CreateDirectoryRequest) (*CreateDirectoryResponse, error)
	DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error)
	RenameFile(context.Context, *RenameFileRequest) (*RenameFileResponse, error)
	mustEmbedUnimplementedFileServiceServer()
}

// UnimplementedFileServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileServiceServer struct{}

func (UnimplementedFileServiceServer) ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedFileServiceServer) ReadTextFile(context.Context, *ReadTextFileRequest) (*ReadTextFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadTextFile not implemented")
}
func (UnimplementedFileServiceServer) ReadFileChunk(context.Context, *ReadFileChunkRequest) (*ReadFileChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadFileChunk not implemented")
}
func (UnimplementedFileServiceServer) WriteFileChunk(context.Context, *WriteFileChunkRequest) (*WriteFileChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteFileChunk not implemented")
}
func (UnimplementedFileServiceServer) WriteTextFile(context.Context, *WriteTextFileRequest) (*WriteTextFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteTextFile not implemented")
}
func (UnimplementedFileServiceServer) CreateDirectory(context.Context, *CreateDirectoryRequest) (*CreateDirectoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDirectory not implemented")
}
func (UnimplementedFileServiceServer) DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFile not implemented")
}
func (UnimplementedFileServiceServer) RenameFile(context.Context, *RenameFileRequest) (*RenameFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenameFile not implemented")
}
func (UnimplementedFileServiceServer) mustEmbedUnimplementedFileServiceServer() {}
func (UnimplementedFileServiceServer) testEmbeddedByValue()                     {}

// UnsafeFileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileServiceServer will
// result in compilation errors.
type UnsafeFileServiceServer interface {
	mustEmbedUnimplementedFileServiceServer()
}

func RegisterFileServiceServer(s grpc.ServiceRegistrar, srv FileServiceServer) {
	// If the following call pancis, it indicates UnimplementedFileServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileService_ServiceDesc, srv)
}

func _FileService_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).ListFiles(ctx, req.(*ListFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_ReadTextFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadTextFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).ReadTextFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_ReadTextFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).ReadTextFile(ctx, req.(*ReadTextFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_ReadFileChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadFileChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).ReadFileChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_ReadFileChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).ReadFileChunk(ctx, req.(*ReadFileChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_WriteFileChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteFileChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).WriteFileChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_WriteFileChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).WriteFileChunk(ctx, req.(*WriteFileChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_WriteTextFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteTextFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).WriteTextFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_WriteTextFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).WriteTextFile(ctx, req.(*WriteTextFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_CreateDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).CreateDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_CreateDirectory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).CreateDirectory(ctx, req.(*CreateDirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_DeleteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).DeleteFile(ctx, req.(*DeleteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_RenameFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).RenameFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_RenameFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).RenameFile(ctx, req.(*RenameFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FileService_ServiceDesc is the grpc.ServiceDesc for FileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "snowpanel.agent.v1.FileService",
	HandlerType: (*FileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFiles",
			Handler:    _FileService_ListFiles_Handler,
		},
		{
			MethodName: "ReadTextFile",
			Handler:    _FileService_ReadTextFile_Handler,
		},
		{
			MethodName: "ReadFileChunk",
			Handler:    _FileService_ReadFileChunk_Handler,
		},
		{
			MethodName: "WriteFileChunk",
			Handler:    _FileService_WriteFileChunk_Handler,
		},
		{
			MethodName: "WriteTextFile",
			Handler:    _FileService_WriteTextFile_Handler,
		},
		{
			MethodName: "CreateDirectory",
			Handler:    _FileService_CreateDirectory_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _FileService_DeleteFile_Handler,
		},
		{
			MethodName: "RenameFile",
			Handler:    _FileService_RenameFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/agent/v1/agent.proto",
}

const (
	ServiceManagerService_ListServices_FullMethodName   = "/snowpanel.agent.v1.ServiceManagerService/ListServices"
	ServiceManagerService_StartService_FullMethodName   = "/snowpanel.agent.v1.ServiceManagerService/StartService"
	ServiceManagerService_StopService_FullMethodName    = "/snowpanel.agent.v1.ServiceManagerService/StopService"
	ServiceManagerService_RestartService_FullMethodName = "/snowpanel.agent.v1.ServiceManagerService/RestartService"
)

// ServiceManagerServiceClient is the client API for ServiceManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceManagerServiceClient interface {
	ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error)
	StartService(ctx context.Context, in *ServiceActionRequest, opts ...grpc.CallOption) (*ServiceActionResponse, error)
	StopService(ctx context.Context, in *ServiceActionRequest, opts ...grpc.CallOption) (*ServiceActionResponse, error)
	RestartService(ctx context.Context, in *ServiceActionRequest, opts ...grpc.CallOption) (*ServiceActionResponse, error)
}

type serviceManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceManagerServiceClient(cc grpc.ClientConnInterface) ServiceManagerServiceClient {
	return &serviceManagerServiceClient{cc}
}

func (c *serviceManagerServiceClient) ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServicesResponse)
	err := c.cc.Invoke(ctx, ServiceManagerService_ListServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagerServiceClient) StartService(ctx context.Context, in *ServiceActionRequest, opts ...grpc.CallOption) (*ServiceActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceActionResponse)
	err := c.cc.Invoke(ctx, ServiceManagerService_StartService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagerServiceClient) StopService(ctx context.Context, in *ServiceActionRequest, opts ...grpc.CallOption) (*ServiceActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceActionResponse)
	err := c.cc.Invoke(ctx, ServiceManagerService_StopService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagerServiceClient) RestartService(ctx context.Context, in *ServiceActionRequest, opts ...grpc.CallOption) (*ServiceActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceActionResponse)
	err := c.cc.Invoke(ctx, ServiceManagerService_RestartService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceManagerServiceServer is the server API for ServiceManagerService service.
// All implementations must embed UnimplementedServiceManagerServiceServer
// for forward compatibility.
type ServiceManagerServiceServer interface {
	ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error)
	StartService(context.Context, *ServiceActionRequest) (*ServiceActionResponse, error)
	StopService(context.Context, *ServiceActionRequest) (*ServiceActionResponse, error)
	RestartService(context.Context, *ServiceActionRequest) (*ServiceActionResponse, error)
	mustEmbedUnimplementedServiceManagerServiceServer()
}

// UnimplementedServiceManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceManagerServiceServer struct{}

func (UnimplementedServiceManagerServiceServer) ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedServiceManagerServiceServer) StartService(context.Context, *ServiceActionRequest) (*ServiceActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartService not implemented")
}
func (UnimplementedServiceManagerServiceServer) StopService(context.Context, *ServiceActionRequest) (*ServiceActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopService not implemented")
}
func (UnimplementedServiceManagerServiceServer) RestartService(context.Context, *ServiceActionRequest) (*ServiceActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestartService not implemented")
}
func (UnimplementedServiceManagerServiceServer) mustEmbedUnimplementedServiceManagerServiceServer() {}
func (UnimplementedServiceManagerServiceServer) testEmbeddedByValue()                               {}

// UnsafeServiceManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceManagerServiceServer will
// result in compilation errors.
type UnsafeServiceManagerServiceServer interface {
	mustEmbedUnimplementedServiceManagerServiceServer()
}

func RegisterServiceManagerServiceServer(s grpc.ServiceRegistrar, srv ServiceManagerServiceServer) {
	// If the following call pancis, it indicates UnimplementedServiceManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServiceManagerService_ServiceDesc, srv)
}

func _ServiceManagerService_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServiceServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceManagerService_ListServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServiceServer).ListServices(ctx, req.(*ListServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManagerService_StartService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServiceServer).StartService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceManagerService_StartService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServiceServer).StartService(ctx, req.(*ServiceActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManagerService_StopService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServiceServer).StopService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceManagerService_StopService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServiceServer).StopService(ctx, req.(*ServiceActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManagerService_RestartService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServiceServer).RestartService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceManagerService_RestartService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServiceServer).RestartService(ctx, req.(*ServiceActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceManagerService_ServiceDesc is the grpc.ServiceDesc for ServiceManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "snowpanel.agent.v1.ServiceManagerService",
	HandlerType: (*ServiceManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListServices",
			Handler:    _ServiceManagerService_ListServices_Handler,
		},
		{
			MethodName: "StartService",
			Handler:    _ServiceManagerService_StartService_Handler,
		},
		{
			MethodName: "StopService",
			Handler:    _ServiceManagerService_StopService_Handler,
		},
		{
			MethodName: "RestartService",
			Handler:    _ServiceManagerService_RestartService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/agent/v1/agent.proto",
}

const (
	DockerService_ListContainers_FullMethodName   = "/snowpanel.agent.v1.DockerService/ListContainers"
	DockerService_StartContainer_FullMethodName   = "/snowpanel.agent.v1.DockerService/StartContainer"
	DockerService_StopContainer_FullMethodName    = "/snowpanel.agent.v1.DockerService/StopContainer"
	DockerService_RestartContainer_FullMethodName = "/snowpanel.agent.v1.DockerService/RestartContainer"
	DockerService_ListImages_FullMethodName       = "/snowpanel.agent.v1.DockerService/ListImages"
)

// DockerServiceClient is the client API for DockerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DockerServiceClient interface {
	ListContainers(ctx context.Context, in *ListDockerContainersRequest, opts ...grpc.CallOption) (*ListDockerContainersResponse, error)
	StartContainer(ctx context.Context, in *DockerContainerActionRequest, opts ...grpc.CallOption) (*DockerContainerActionResponse, error)
	StopContainer(ctx context.Context, in *DockerContainerActionRequest, opts ...grpc.CallOption) (*DockerContainerActionResponse, error)
	RestartContainer(ctx context.Context, in *DockerContainerActionRequest, opts ...grpc.CallOption) (*DockerContainerActionResponse, error)
	ListImages(ctx context.Context, in *ListDockerImagesRequest, opts ...grpc.CallOption) (*ListDockerImagesResponse, error)
}

type dockerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDockerServiceClient(cc grpc.ClientConnInterface) DockerServiceClient {
	return &dockerServiceClient{cc}
}

func (c *dockerServiceClient) ListContainers(ctx context.Context, in *ListDockerContainersRequest, opts ...grpc.CallOption) (*ListDockerContainersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDockerContainersResponse)
	err := c.cc.Invoke(ctx, DockerService_ListContainers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) StartContainer(ctx context.Context, in *DockerContainerActionRequest, opts ...grpc.CallOption) (*DockerContainerActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DockerContainerActionResponse)
	err := c.cc.Invoke(ctx, DockerService_StartContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) StopContainer(ctx context.Context, in *DockerContainerActionRequest, opts ...grpc.CallOption) (*DockerContainerActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DockerContainerActionResponse)
	err := c.cc.Invoke(ctx, DockerService_StopContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) RestartContainer(ctx context.Context, in *DockerContainerActionRequest, opts ...grpc.CallOption) (*DockerContainerActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DockerContainerActionResponse)
	err := c.cc.Invoke(ctx, DockerService_RestartContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) ListImages(ctx context.Context, in *ListDockerImagesRequest, opts ...grpc.CallOption) (*ListDockerImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDockerImagesResponse)
	err := c.cc.Invoke(ctx, DockerService_ListImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DockerServiceServer is the server API for DockerService service.
// All implementations must embed UnimplementedDockerServiceServer
// for forward compatibility.
type DockerServiceServer interface {
	ListContainers(context.Context, *ListDockerContainersRequest) (*ListDockerContainersResponse, error)
	StartContainer(context.Context, *DockerContainerActionRequest) (*DockerContainerActionResponse, error)
	StopContainer(context.Context, *DockerContainerActionRequest) (*DockerContainerActionResponse, error)
	RestartContainer(context.Context, *DockerContainerActionRequest) (*DockerContainerActionResponse, error)
	ListImages(context.Context, *ListDockerImagesRequest) (*ListDockerImagesResponse, error)
	mustEmbedUnimplementedDockerServiceServer()
}

// UnimplementedDockerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDockerServiceServer struct{}

func (UnimplementedDockerServiceServer) ListContainers(context.Context, *ListDockerContainersRequest) (*ListDockerContainersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListContainers not implemented")
}
func (UnimplementedDockerServiceServer) StartContainer(context.Context, *DockerContainerActionRequest) (*DockerContainerActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartContainer not implemented")
}
func (UnimplementedDockerServiceServer) StopContainer(context.Context, *DockerContainerActionRequest) (*DockerContainerActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopContainer not implemented")
}
func (UnimplementedDockerServiceServer) RestartContainer(context.Context, *DockerContainerActionRequest) (*DockerContainerActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestartContainer not implemented")
}
func (UnimplementedDockerServiceServer) ListImages(context.Context, *ListDockerImagesRequest) (*ListDockerImagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListImages not implemented")
}
func (UnimplementedDockerServiceServer) mustEmbedUnimplementedDockerServiceServer() {}
func (UnimplementedDockerServiceServer) testEmbeddedByValue()                       {}

// UnsafeDockerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DockerServiceServer will
// result in compilation errors.
type UnsafeDockerServiceServer interface {
	mustEmbedUnimplementedDockerServiceServer()
}

func RegisterDockerServiceServer(s grpc.ServiceRegistrar, srv DockerServiceServer) {
	// If the following call pancis, it indicates UnimplementedDockerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DockerService_ServiceDesc, srv)
}

func _DockerService_ListContainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDockerContainersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).ListContainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_ListContainers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).ListContainers(ctx, req.(*ListDockerContainersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_StartContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DockerContainerActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).StartContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_StartContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).StartContainer(ctx, req.(*DockerContainerActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_StopContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DockerContainerActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).StopContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_StopContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).StopContainer(ctx, req.(*DockerContainerActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_RestartContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DockerContainerActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).RestartContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_RestartContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).RestartContainer(ctx, req.(*DockerContainerActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_ListImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDockerImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).ListImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_ListImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).ListImages(ctx, req.(*ListDockerImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DockerService_ServiceDesc is the grpc.ServiceDesc for DockerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DockerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "snowpanel.agent.v1.DockerService",
	HandlerType: (*DockerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListContainers",
			Handler:    _DockerService_ListContainers_Handler,
		},
		{
			MethodName: "StartContainer",
			Handler:    _DockerService_StartContainer_Handler,
		},
		{
			MethodName: "StopContainer",
			Handler:    _DockerService_StopContainer_Handler,
		},
		{
			MethodName: "RestartContainer",
			Handler:    _DockerService_RestartContainer_Handler,
		},
		{
			MethodName: "ListImages",
			Handler:    _DockerService_ListImages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/agent/v1/agent.proto",
}

const (
	CronService_ListCronTasks_FullMethodName      = "/snowpanel.agent.v1.CronService/ListCronTasks"
	CronService_CreateCronTask_FullMethodName     = "/snowpanel.agent.v1.CronService/CreateCronTask"
	CronService_UpdateCronTask_FullMethodName     = "/snowpanel.agent.v1.CronService/UpdateCronTask"
	CronService_DeleteCronTask_FullMethodName     = "/snowpanel.agent.v1.CronService/DeleteCronTask"
	CronService_SetCronTaskEnabled_FullMethodName = "/snowpanel.agent.v1.CronService/SetCronTaskEnabled"
)

// CronServiceClient is the client API for CronService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CronServiceClient interface {
	ListCronTasks(ctx context.Context, in *ListCronTasksRequest, opts ...grpc.CallOption) (*ListCronTasksResponse, error)
	CreateCronTask(ctx context.Context, in *CreateCronTaskRequest, opts ...grpc.CallOption) (*CreateCronTaskResponse, error)
	UpdateCronTask(ctx context.Context, in *UpdateCronTaskRequest, opts ...grpc.CallOption) (*UpdateCronTaskResponse, error)
	DeleteCronTask(ctx context.Context, in *DeleteCronTaskRequest, opts ...grpc.CallOption) (*DeleteCronTaskResponse, error)
	SetCronTaskEnabled(ctx context.Context, in *SetCronTaskEnabledRequest, opts ...grpc.CallOption) (*SetCronTaskEnabledResponse, error)
}

type cronServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCronServiceClient(cc grpc.ClientConnInterface) CronServiceClient {
	return &cronServiceClient{cc}
}

func (c *cronServiceClient) ListCronTasks(ctx context.Context, in *ListCronTasksRequest, opts ...grpc.CallOption) (*ListCronTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCronTasksResponse)
	err := c.cc.Invoke(ctx, CronService_ListCronTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronServiceClient) CreateCronTask(ctx context.Context, in *CreateCronTaskRequest, opts ...grpc.CallOption) (*CreateCronTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCronTaskResponse)
	err := c.cc.Invoke(ctx, CronService_CreateCronTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronServiceClient) UpdateCronTask(ctx context.Context, in *UpdateCronTaskRequest, opts ...grpc.CallOption) (*UpdateCronTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCronTaskResponse)
	err := c.cc.Invoke(ctx, CronService_UpdateCronTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronServiceClient) DeleteCronTask(ctx context.Context, in *DeleteCronTaskRequest, opts ...grpc.CallOption) (*DeleteCronTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCronTaskResponse)
	err := c.cc.Invoke(ctx, CronService_DeleteCronTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronServiceClient) SetCronTaskEnabled(ctx context.Context, in *SetCronTaskEnabledRequest, opts ...grpc.CallOption) (*SetCronTaskEnabledResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetCronTaskEnabledResponse)
	err := c.cc.Invoke(ctx, CronService_SetCronTaskEnabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CronServiceServer is the server API for CronService service.
// All implementations must embed UnimplementedCronServiceServer
// for forward compatibility.
type CronServiceServer interface {
	ListCronTasks(context.Context, *ListCronTasksRequest) (*ListCronTasksResponse, error)
	CreateCronTask(context.Context, *CreateCronTaskRequest) (*CreateCronTaskResponse, error)
	UpdateCronTask(context.Context, *UpdateCronTaskRequest) (*UpdateCronTaskResponse, error)
	DeleteCronTask(context.Context, *DeleteCronTaskRequest) (*DeleteCronTaskResponse, error)
	SetCronTaskEnabled(context.Context, *SetCronTaskEnabledRequest) (*SetCronTaskEnabledResponse, error)
	mustEmbedUnimplementedCronServiceServer()
}

// UnimplementedCronServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCronServiceServer struct{}

func (UnimplementedCronServiceServer) ListCronTasks(context.Context, *ListCronTasksRequest) (*ListCronTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCronTasks not implemented")
}
func (UnimplementedCronServiceServer) CreateCronTask(context.Context, *CreateCronTaskRequest) (*CreateCronTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCronTask not implemented")
}
func (UnimplementedCronServiceServer) UpdateCronTask(context.Context, *UpdateCronTaskRequest) (*UpdateCronTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCronTask not implemented")
}
func (UnimplementedCronServiceServer) DeleteCronTask(context.Context, *DeleteCronTaskRequest) (*DeleteCronTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCronTask not implemented")
}
func (UnimplementedCronServiceServer) SetCronTaskEnabled(context.Context, *SetCronTaskEnabledRequest) (*SetCronTaskEnabledResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCronTaskEnabled not implemented")
}
func (UnimplementedCronServiceServer) mustEmbedUnimplementedCronServiceServer() {}
func (UnimplementedCronServiceServer) testEmbeddedByValue()                     {}

// UnsafeCronServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CronServiceServer will
// result in compilation errors.
type UnsafeCronServiceServer interface {
	mustEmbedUnimplementedCronServiceServer()
}

func RegisterCronServiceServer(s grpc.ServiceRegistrar, srv CronServiceServer) {
	// If the following call pancis, it indicates UnimplementedCronServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CronService_ServiceDesc, srv)
}

func _CronService_ListCronTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCronTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServiceServer).ListCronTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronService_ListCronTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServiceServer).ListCronTasks(ctx, req.(*ListCronTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CronService_CreateCronTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCronTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServiceServer).CreateCronTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronService_CreateCronTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServiceServer).CreateCronTask(ctx, req.(*CreateCronTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CronService_UpdateCronTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCronTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServiceServer).UpdateCronTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronService_UpdateCronTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServiceServer).UpdateCronTask(ctx, req.(*UpdateCronTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CronService_DeleteCronTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCronTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServiceServer).DeleteCronTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronService_DeleteCronTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServiceServer).DeleteCronTask(ctx, req.(*DeleteCronTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CronService_SetCronTaskEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCronTaskEnabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServiceServer).SetCronTaskEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronService_SetCronTaskEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServiceServer).SetCronTaskEnabled(ctx, req.(*SetCronTaskEnabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CronService_ServiceDesc is the grpc.ServiceDesc for CronService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CronService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "snowpanel.agent.v1.CronService",
	HandlerType: (*CronServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCronTasks",
			Handler:    _CronService_ListCronTasks_Handler,
		},
		{
			MethodName: "CreateCronTask",
			Handler:    _CronService_CreateCronTask_Handler,
		},
		{
			MethodName: "UpdateCronTask",
			Handler:    _CronService_UpdateCronTask_Handler,
		},
		{
			MethodName: "DeleteCronTask",
			Handler:    _CronService_DeleteCronTask_Handler,
		},
		{
			MethodName: "SetCronTaskEnabled",
			Handler:    _CronService_SetCronTaskEnabled_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/agent/v1/agent.proto",
}
